import { useState } from 'react';
import { Search, FileText, Download, Share2, CheckCircle2, TrendingUp, BarChart3, ShieldCheck } from 'lucide-react';
import InspectionList, { Inspection } from '../components/InspectionList';
import { Language } from '../i18n';


interface ReportsScreenProps {
  inspections: Inspection[];
  onRowClick: (id: string) => void;
  onSearchClick?: () => void;
  language?: Language;
}

export default function ReportsScreen({ inspections, onRowClick, onSearchClick, language = 'en' }: ReportsScreenProps) {
  const [selectedId, setSelectedId] = useState<string>(inspections[0]?.id || '8042');
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 2500);
  };

  const activeInspection = inspections.find(i => i.id === selectedId) || inspections[0] || {
    id: '8042',
    title: 'Premium Basmati Rice',
    meta: 'Food Grains · Warehouse A, New Delhi',
    status: 'NON_COMPLIANT' as const,
    timeInfo: 'Today'
  };

  const isNonCompliant = (activeInspection.status as string) === 'NON_COMPLIANT';
  const isReview = (activeInspection.status as string) === 'REVIEW' || (activeInspection.status as string) === 'REQUIRES_REVIEW';
  const totalRules = 5;
  const failCount = isNonCompliant ? 2 : 0;
  const reviewCount = isReview ? 1 : 0;
  const passCount = totalRules - failCount - reviewCount;
  const passRate = Math.round((passCount / totalRules) * 100);



  const handleGeneratePdf = () => {
    // Generate a printable report window for immediate preview and print/save to PDF
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Legal Metrology Inspection Notice #${activeInspection.id}</title>
          <style>
            body { font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px; color: #111; line-height: 1.5; }
            h1 { margin-bottom: 4px; font-size: 24px; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px; font-weight: bold; background: #fee2e2; color: #b91c1c; margin-bottom: 20px; }
            .section { margin-top: 24px; border-top: 1px solid #e5e7eb; pt: 16px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 16px 0; }
            .card { background: #f9fafb; padding: 12px; border-radius: 8px; font-size: 13px; }
            .footer { margin-top: 40px; font-size: 11px; color: #6b7280; text-align: center; }
          </style>
        </head>
        <body>
          <h1>PaarakhMetric Legal Metrology Notice</h1>
          <div class="badge">RECORD #${activeInspection.id} · STATUS: ${activeInspection.status}</div>
          <p><strong>Product Name:</strong> ${activeInspection.title}</p>
          <p><strong>Details / Location:</strong> ${activeInspection.meta}</p>
          
          <div class="section">
            <h3>Statutory Evaluation Findings</h3>
            <div class="grid">
              <div class="card"><strong>Rule PC-MRP-001:</strong> Retail Sale Price verification checked.</div>
              <div class="card"><strong>Rule PC-DATE-003:</strong> Month & Year of packing verified.</div>
              <div class="card"><strong>Rule PC-QTY-002:</strong> Standard units of measure check.</div>
              <div class="card"><strong>Rule PC-CARE-004:</strong> Consumer grievance helpline presence.</div>
            </div>
          </div>
          <div class="footer">Generated by PaarakhMetric AI Compliance Assistant · Legal Metrology (Packaged Commodities) Rules</div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => printWindow.print(), 300);
      showToast('PDF inspection report generated!');
    } else {
      window.open(`/api/inspections/${activeInspection.id}/pdf-report`, '_blank');
      showToast('Opening PDF report...');
    }
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: `PaarakhMetric Inspection #${activeInspection.id}`,
        text: `Inspection Report for ${activeInspection.title} - Status: ${activeInspection.status}`,
        url: window.location.href
      }).catch(() => {});
    } else {
      navigator.clipboard?.writeText?.(window.location.href);
      showToast('Report link copied to clipboard!');
    }
  };

  return (
    <div className="flex flex-col gap-6 relative">
      {/* Toast */}
      {toastMessage && (
        <div className="fixed top-6 left-1/2 -translate-x-1/2 z-[250] bg-surface-elevated text-fg border border-divider px-4 py-2 rounded-full shadow-lg text-xs font-semibold flex items-center gap-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-success" />
          <span>{toastMessage}</span>
        </div>
      )}

      <section className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <FileText className="w-9 h-9 text-accent" />
          <h1 className="font-display text-[28px] leading-[32px] font-bold tracking-tight m-0">Reports</h1>
        </div>
        <button 
          onClick={onSearchClick}
          className="w-10 h-10 rounded-full bg-surface text-fg flex items-center justify-center transition-colors hover:bg-surface-elevated focus-visible:outline focus-visible:outline-2 focus-visible:outline-fg focus-visible:outline-offset-2 active:scale-95 flex-shrink-0"
          title="Search Records"
        >
          <Search className="w-5 h-5" />
        </button>
      </section>

      {/* Featured Inspection Report Card */}
      <section className="bg-surface rounded-2xl p-6 flex flex-col gap-6 relative overflow-hidden">
        <div className="flex items-center justify-between">
          <span className="text-[12px] tracking-[0.08em] uppercase text-fg-muted font-semibold">Inspection #{activeInspection.id}</span>
          <span className={`inline-flex items-center gap-2 px-3 py-2 rounded-full text-[12px] font-semibold tracking-[0.02em] bg-transparent border border-divider ${
            activeInspection.status === 'COMPLIANT' ? 'text-success' : activeInspection.status === 'NON_COMPLIANT' ? 'text-error' : 'text-warning'
          }`}>
            <span className="w-1.5 h-1.5 rounded-full bg-current"></span>
            {activeInspection.status === 'COMPLIANT' ? 'Compliant' : activeInspection.status === 'NON_COMPLIANT' ? 'Non-compliant' : 'Review'}
          </span>
        </div>

        <div>
          <div className="font-display text-[28px] font-bold">{activeInspection.title}</div>
          <div className="text-[13px] whitespace-nowrap overflow-hidden text-ellipsis text-fg-muted">
            {activeInspection.meta} · Officer Shrey
          </div>
        </div>

        {/* Visual Compliance Graphs & Trends */}
        <div className="bg-surface-recessed/60 rounded-xl p-4 border border-divider/60 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <span className="text-[11px] tracking-[0.08em] uppercase text-fg-muted font-bold flex items-center gap-1.5">
              <TrendingUp className="w-3.5 h-3.5 text-accent" />
              {language === 'hi' ? 'अनुपालन रुझान और स्वास्थ्य स्कोर' : language === 'kn' ? 'ಅನುಸರಣೆ ಟ್ರೆಂಡ್‌ಗಳು & ಸ್ಕೋರ್' : 'Compliance Trends & Health Analytics'}
            </span>
            <span className={`text-[11px] font-bold px-2 py-0.5 rounded-full ${
              passRate >= 80 ? 'bg-success/15 text-success' : passRate >= 60 ? 'bg-warning/15 text-warning' : 'bg-error/15 text-error'
            }`}>
              {passRate}% {language === 'hi' ? 'अनुपालन दर' : language === 'kn' ? 'ದರ' : 'Score'}
            </span>
          </div>

          {/* Metric Bar Distribution */}
          <div className="flex flex-col gap-1.5">
            <div className="flex justify-between text-[11px] font-medium text-fg-muted">
              <span>{language === 'hi' ? 'नियम सत्यापन वितरण' : language === 'kn' ? 'ನಿಯಮ ಪರಿಶೀಲನೆ' : 'Statutory Rule Breakdown'}</span>
              <span className="font-mono text-fg">{passCount} Pass · {failCount} Fail · {reviewCount} Review</span>
            </div>
            {/* Multi-segment Progress Bar */}
            <div className="w-full h-3 bg-surface-elevated rounded-full overflow-hidden flex gap-0.5 p-0.5">
              <div style={{ width: `${(passCount / totalRules) * 100}%` }} className="bg-success rounded-l-full transition-all duration-500" title={`Pass: ${passCount}`} />
              {reviewCount > 0 && (
                <div style={{ width: `${(reviewCount / totalRules) * 100}%` }} className="bg-warning transition-all duration-500" title={`Review: ${reviewCount}`} />
              )}
              {failCount > 0 && (
                <div style={{ width: `${(failCount / totalRules) * 100}%` }} className="bg-error rounded-r-full transition-all duration-500" title={`Fail: ${failCount}`} />
              )}
            </div>
          </div>

          {/* 7-Day Category Compliance Trend Chart */}
          <div className="flex flex-col gap-2 pt-2 border-t border-divider/40">
            <div className="flex items-center justify-between text-[11px]">
              <span className="text-fg-muted font-medium flex items-center gap-1">
                <BarChart3 className="w-3 h-3 text-accent" />
                {language === 'hi' ? '7 दिवसीय श्रेणी अनुपालन रुझान' : language === 'kn' ? '7 ದಿನದ ವರ್ಗ ಟ್ರೆಂಡ್' : '7-Day Category Compliance Trend'}
              </span>
              <span className="text-[10px] text-accent font-semibold">
                {activeInspection.meta?.split('·')?.[0]?.trim() || 'General'}
              </span>
            </div>

            {/* Mini Bar Chart */}
            <div className="flex items-end justify-between gap-2 h-16 pt-2 px-1">
              {[
                { day: 'Mon', val: 92 },
                { day: 'Tue', val: 86 },
                { day: 'Wed', val: 78 },
                { day: 'Thu', val: 94 },
                { day: 'Fri', val: passRate },
                { day: 'Sat', val: 88 },
                { day: 'Sun', val: 95 }
              ].map((item, idx) => (
                <div key={idx} className="flex-1 flex flex-col items-center gap-1 group">
                  <div className="relative w-full flex items-end justify-center h-10 bg-surface-elevated/40 rounded-t">
                    <div 
                      style={{ height: `${item.val}%` }} 
                      className={`w-full rounded-t transition-all duration-500 ${
                        item.day === 'Fri' ? (passRate < 70 ? 'bg-error' : 'bg-accent') : item.val > 85 ? 'bg-success/70' : 'bg-warning/70'
                      }`} 
                    />
                    {/* Tooltip */}
                    <div className="absolute -top-6 bg-fg text-canvas text-[9px] font-bold px-1.5 py-0.5 rounded opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-10">
                      {item.val}%
                    </div>
                  </div>
                  <span className={`text-[9px] font-medium ${item.day === 'Fri' ? 'text-accent font-bold' : 'text-fg-muted'}`}>
                    {item.day}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Extraction Quality Meters */}
          <div className="grid grid-cols-2 gap-2 pt-2 border-t border-divider/40">
            <div className="flex flex-col gap-1 bg-surface-elevated/50 p-2 rounded-lg">
              <span className="text-[10px] text-fg-muted font-medium">{language === 'hi' ? 'एआई दृष्टि विश्वास' : language === 'kn' ? 'AI ವಿಶ್ವಾಸ' : 'Vision OCR Accuracy'}</span>
              <div className="flex items-center justify-between">
                <span className="text-[13px] font-bold font-mono text-fg">94.8%</span>
                <span className="text-[10px] text-success font-semibold flex items-center gap-0.5">
                  <ShieldCheck className="w-3 h-3" /> High
                </span>
              </div>
            </div>

            <div className="flex flex-col gap-1 bg-surface-elevated/50 p-2 rounded-lg">
              <span className="text-[10px] text-fg-muted font-medium">{language === 'hi' ? 'वैधानिक जोखिम रेटिंग' : language === 'kn' ? 'ಅಪಾಯ ರೇಟಿಂಗ್' : 'Commodity Risk'}</span>
              <div className="flex items-center justify-between">
                <span className="text-[13px] font-bold text-fg">
                  {failCount > 0 ? (language === 'hi' ? 'उच्च जोखिम' : language === 'kn' ? 'ಹೆಚ್ಚು' : 'Elevated') : (language === 'hi' ? 'कम जोखिम' : language === 'kn' ? 'ಕಡಿಮೆ' : 'Low Risk')}
                </span>
                <span className={`text-[10px] font-semibold ${failCount > 0 ? 'text-error' : 'text-success'}`}>
                  {failCount > 0 ? 'Action Req.' : 'Nominal'}
                </span>
              </div>
            </div>
          </div>
        </div>


        <div className="flex gap-3">
          <button 
            onClick={handleGeneratePdf}
            className="flex-1 flex items-center justify-center gap-2 bg-accent text-on-accent rounded-full p-4 text-[16px] font-bold active:scale-95 transition-transform"
          >
            <Download className="w-5 h-5" />
            Generate PDF
          </button>
          <button 
            onClick={handleShare}
            className="w-14 flex-shrink-0 flex items-center justify-center bg-surface-elevated text-fg rounded-full active:scale-95 transition-transform hover:text-accent"
            title="Share Report"
          >
            <Share2 className="w-5 h-5" />
          </button>
        </div>

        <div className="text-[12px] text-fg-muted text-center">
          Report available for print or instant dispatch · {activeInspection.timeInfo || 'Today'}
        </div>
      </section>

      {/* Rule verdicts overview */}
      <section className="flex flex-col gap-3">
        <span className="text-[12px] tracking-[0.08em] uppercase text-fg-muted font-semibold">Rule verdicts</span>
        <div className="flex flex-col gap-3">
          <div className="bg-surface rounded-2xl p-4 flex items-center gap-3">
            <div className="flex-1 min-w-0 flex flex-col gap-0.5">
              <span className="text-[16px] font-semibold text-fg whitespace-nowrap overflow-hidden text-ellipsis">PC-MRP-001 · Retail sale price</span>
              <span className="text-[13px] text-fg-muted whitespace-nowrap overflow-hidden text-ellipsis">
                {activeInspection.status === 'NON_COMPLIANT' ? 'Missing numerical characters in MRP field' : 'MRP detected and compliant with tax inclusion'}
              </span>
            </div>
            <span className={`flex-shrink-0 inline-flex items-center gap-2 px-3 py-2 rounded-full text-[12px] font-semibold tracking-[0.02em] bg-transparent border border-divider ${
              activeInspection.status === 'NON_COMPLIANT' ? 'text-error' : 'text-success'
            }`}>
              <span className="w-1.5 h-1.5 rounded-full bg-current"></span>
              {activeInspection.status === 'NON_COMPLIANT' ? 'Fail' : 'Pass'}
            </span>
          </div>

          <div className="bg-surface rounded-2xl p-4 flex items-center gap-3">
            <div className="flex-1 min-w-0 flex flex-col gap-0.5">
              <span className="text-[16px] font-semibold text-fg whitespace-nowrap overflow-hidden text-ellipsis">PC-DATE-003 · Packing date</span>
              <span className="text-[13px] text-fg-muted whitespace-nowrap overflow-hidden text-ellipsis">MM/YYYY format matched: 08/2026</span>
            </div>
            <span className="flex-shrink-0 inline-flex items-center gap-2 px-3 py-2 rounded-full text-[12px] font-semibold tracking-[0.02em] bg-transparent border border-divider text-success">
              <span className="w-1.5 h-1.5 rounded-full bg-current"></span>Pass
            </span>
          </div>
        </div>
      </section>

      {/* Past Reports List */}
      <InspectionList 
        title="Select inspection report"
        inspections={inspections.map(i => ({...i, iconType: 'FileText'}))} 
        onRowClick={(id) => {
          setSelectedId(id);
          onRowClick(id);
        }} 
      />
    </div>
  );
}
